package pe.com.dentalamericana.finance;
import jakarta.servlet.http.HttpServletRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import pe.com.dentalamericana.audit.*;import pe.com.dentalamericana.common.*;import pe.com.dentalamericana.finance.dto.FinanceDtos.*;import pe.com.dentalamericana.patient.*;import pe.com.dentalamericana.security.AuthenticatedUser;import pe.com.dentalamericana.treatment.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
@Service public class FinanceService{
 private final PaymentMethodRepository methods;private final ReceivableAccountRepository accounts;private final CashSessionRepository sessions;private final PaymentRepository payments;private final ExpenseRepository expenses;private final CashMovementRepository movements;private final TreatmentPlanRepository plans;private final PatientService patients;private final AuditService audit;
 public FinanceService(PaymentMethodRepository methods,ReceivableAccountRepository accounts,CashSessionRepository sessions,PaymentRepository payments,ExpenseRepository expenses,CashMovementRepository movements,TreatmentPlanRepository plans,PatientService patients,AuditService audit){this.methods=methods;this.accounts=accounts;this.sessions=sessions;this.payments=payments;this.expenses=expenses;this.movements=movements;this.plans=plans;this.patients=patients;this.audit=audit;}
 @Transactional(readOnly=true)public List<MethodResponse>methods(){return methods.findAllByActivoTrueOrderByNombreAsc().stream().map(MethodResponse::from).toList();}
 @Transactional(readOnly=true)public List<AccountResponse>accounts(ReceivableStatus status,Long patientId){List<ReceivableAccount>list=patientId!=null?accounts.findAllByPatientIdOrderByUpdatedAtDesc(patientId):status!=null?accounts.findAllByEstadoOrderByUpdatedAtDesc(status):accounts.findAllByOrderByUpdatedAtDesc();return list.stream().map(this::account).toList();}
 @Transactional(readOnly=true)public CashSessionResponse current(){return sessions.findFirstByEstadoOrderByOpenedAtDesc(CashSessionStatus.ABIERTA).map(this::session).orElse(null);}
 @Transactional public CashSessionResponse open(OpenCashRequest r,AuthenticatedUser actor,HttpServletRequest http){if(sessions.findFirstByEstadoOrderByOpenedAtDesc(CashSessionStatus.ABIERTA).isPresent())throw new BusinessConflictException("Ya existe una caja abierta");CashSession s=sessions.save(new CashSession(actor.getId(),r.openingAmount()));record(actor,"ABRIR_CAJA",s.getId(),"Apertura "+r.openingAmount(),http);return session(s);}
 @Transactional public CashSessionResponse close(Long id,CloseCashRequest r,AuthenticatedUser actor,HttpServletRequest http){CashSession s=sessions.findById(id).orElseThrow(()->new ResourceNotFoundException("Caja no encontrada"));if(s.getStatus()!=CashSessionStatus.ABIERTA)throw new BusinessConflictException("La caja ya está cerrada");if(!s.getVersion().equals(r.version()))throw new BusinessConflictException("La caja fue modificada");BigDecimal expected=expectedCash(s);s.close(actor.getId(),expected,r.countedAmount(),trim(r.observation()));record(actor,"CERRAR_CAJA",id,"Diferencia "+r.countedAmount().subtract(expected),http);return session(s);}
 @Transactional public PaymentResponse payment(PaymentRequest r,AuthenticatedUser actor,HttpServletRequest http){CashSession s=requireOpen();ReceivableAccount a=accounts.findById(r.accountId()).orElseThrow(()->new ResourceNotFoundException("Cuenta por cobrar no encontrada"));if(a.getStatus()==ReceivableStatus.PAGADA||a.getStatus()==ReceivableStatus.ANULADA)throw new BusinessConflictException("La cuenta no admite pagos");if(r.amount().compareTo(a.getBalance())>0)throw new BusinessConflictException("El pago supera el saldo pendiente");PaymentMethod m=findMethod(r.paymentMethodId());if(m.isReferenceRequired()&&trim(r.reference())==null)throw new BusinessConflictException("El método de pago requiere referencia");String receipt="REC-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();Payment p=payments.saveAndFlush(new Payment(a.getId(),a.getPatientId(),a.getPlanId(),s.getId(),m.getId(),r.amount(),trim(r.reference()),receipt,actor.getId()));a.registerPayment(r.amount());movements.save(new CashMovement(s.getId(),MovementType.INGRESO,"COBRO_TRATAMIENTO","PAGO",p.getId(),m.getId(),r.amount(),"Pago "+receipt,actor.getId()));record(actor,"REGISTRAR_PAGO",p.getId(),receipt+" monto "+r.amount(),http);return payment(p);}
 @Transactional public ExpenseResponse expense(ExpenseRequest r,AuthenticatedUser actor,HttpServletRequest http){CashSession s=requireOpen();PaymentMethod m=findMethod(r.paymentMethodId());Expense e=expenses.saveAndFlush(new Expense(s.getId(),r.category().trim(),r.description().trim(),trim(r.provider()),trim(r.documentReference()),m.getId(),r.amount(),actor.getId()));movements.save(new CashMovement(s.getId(),MovementType.EGRESO,r.category().trim(),"GASTO",e.getId(),m.getId(),r.amount(),r.description().trim(),actor.getId()));record(actor,"REGISTRAR_GASTO",e.getId(),r.category()+" "+r.amount(),http);return expense(e);}
 @Transactional(readOnly=true)public List<PaymentResponse>payments(Instant from,Instant to){range(from,to);return payments.findAllByRegisteredAtBetweenOrderByRegisteredAtDesc(from,to).stream().map(this::payment).toList();}
 @Transactional(readOnly=true)public List<ExpenseResponse>expenses(Instant from,Instant to){range(from,to);return expenses.findAllByRegisteredAtBetweenOrderByRegisteredAtDesc(from,to).stream().map(this::expense).toList();}
 @Transactional(readOnly=true)public FinanceDashboard dashboard(Instant from,Instant to){range(from,to);List<CashMovement>m=movements.findAllByCreatedAtBetweenOrderByCreatedAtDesc(from,to);BigDecimal income=sum(m,MovementType.INGRESO),expense=sum(m,MovementType.EGRESO);BigDecimal receivable=accounts.findAllByOrderByUpdatedAtDesc().stream().filter(a->a.getStatus()!=ReceivableStatus.ANULADA).map(ReceivableAccount::getBalance).reduce(BigDecimal.ZERO,BigDecimal::add);Map<Long,PaymentMethod>methodMap=new HashMap<>();methods.findAll().forEach(x->methodMap.put(x.getId(),x));BigDecimal cash=m.stream().filter(x->x.getType()==MovementType.INGRESO&&methodMap.get(x.getPaymentMethodId())!=null&&"EFECTIVO".equals(methodMap.get(x.getPaymentMethodId()).getCode())).map(CashMovement::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return new FinanceDashboard(income,expense,income.subtract(expense),receivable,cash,income.subtract(cash),(int)m.stream().filter(x->x.getType()==MovementType.INGRESO).count(),(int)m.stream().filter(x->x.getType()==MovementType.EGRESO).count(),m.stream().limit(20).map(this::movement).toList());}
 private AccountResponse account(ReceivableAccount a){TreatmentPlan p=plans.findById(a.getPlanId()).orElseThrow();Patient patient=patients.find(a.getPatientId());String name=String.join(" ",patient.getFirstNames(),patient.getPaternalSurname(),patient.getMaternalSurname()==null?"":patient.getMaternalSurname()).trim();return new AccountResponse(a.getId(),p.getId(),patient.getId(),name,p.getCode(),a.getTotalAmount(),a.getPaidAmount(),a.getBalance(),a.getStatus(),a.getDueDate(),a.getUpdatedAt(),a.getVersion());}
 private PaymentResponse payment(Payment p){Patient patient=patients.find(p.getPatientId());TreatmentPlan plan=plans.findById(p.getPlanId()).orElseThrow();PaymentMethod m=methods.findById(p.getPaymentMethodId()).orElseThrow();String name=patient.getFirstNames()+" "+patient.getPaternalSurname();return new PaymentResponse(p.getId(),p.getAccountId(),p.getPatientId(),name,p.getPlanId(),plan.getCode(),p.getCashSessionId(),m.getId(),m.getName(),p.getAmount(),p.getReference(),p.getReceiptNumber(),p.getStatus(),p.getRegisteredAt());}
 private ExpenseResponse expense(Expense e){PaymentMethod m=methods.findById(e.getPaymentMethodId()).orElseThrow();return new ExpenseResponse(e.getId(),e.getCashSessionId(),e.getCategory(),e.getDescription(),e.getProvider(),e.getDocumentReference(),m.getId(),m.getName(),e.getAmount(),e.getStatus(),e.getRegisteredAt());}
 private MovementResponse movement(CashMovement m){String method=m.getPaymentMethodId()==null?null:methods.findById(m.getPaymentMethodId()).map(PaymentMethod::getName).orElse(null);return new MovementResponse(m.getId(),m.getCashSessionId(),m.getType(),m.getCategory(),m.getSource(),m.getSourceId(),method,m.getAmount(),m.getDescription(),m.getCreatedAt());}
 private CashSessionResponse session(CashSession s){return new CashSessionResponse(s.getId(),s.getOpenedBy(),s.getOpenedAt(),s.getOpeningAmount(),s.getStatus(),s.getClosedBy(),s.getClosedAt(),s.getExpectedAmount(),s.getCountedAmount(),s.getDifference(),s.getClosingObservation(),s.getVersion());}
 private BigDecimal expectedCash(CashSession s){PaymentMethod cash=methods.findAll().stream().filter(m->"EFECTIVO".equals(m.getCode())).findFirst().orElseThrow();BigDecimal delta=movements.findAllByCashSessionIdOrderByCreatedAtDesc(s.getId()).stream().filter(m->Objects.equals(m.getPaymentMethodId(),cash.getId())).map(m->m.getType()==MovementType.INGRESO?m.getAmount():m.getAmount().negate()).reduce(BigDecimal.ZERO,BigDecimal::add);return s.getOpeningAmount().add(delta);}private BigDecimal sum(List<CashMovement>m,MovementType type){return m.stream().filter(x->x.getType()==type).map(CashMovement::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}private CashSession requireOpen(){return sessions.findFirstByEstadoOrderByOpenedAtDesc(CashSessionStatus.ABIERTA).orElseThrow(()->new BusinessConflictException("Abra la caja antes de registrar operaciones"));}private PaymentMethod findMethod(Long id){return methods.findById(id).filter(PaymentMethod::isActive).orElseThrow(()->new ResourceNotFoundException("Método de pago no encontrado"));}private void range(Instant f,Instant t){if(f==null||t==null||!t.isAfter(f)||Duration.between(f,t).toDays()>366)throw new BusinessConflictException("Rango financiero inválido");}private void record(AuthenticatedUser a,String action,Long id,String detail,HttpServletRequest h){audit.record(patients.actorEntity(a),action,"FINANZAS",id.toString(),AuditResult.EXITO,detail,h);}private String trim(String v){return v==null||v.isBlank()?null:v.trim();}
}
