import{CurrencyPipe,DatePipe}from'@angular/common';import{HttpErrorResponse}from'@angular/common/http';import{ChangeDetectionStrategy,Component,OnInit,inject,signal}from'@angular/core';import{FormBuilder,ReactiveFormsModule,Validators}from'@angular/forms';import{LucideAlertTriangle,LucideArrowDownRight,LucideArrowUpRight,LucideBanknote,LucideCheck,LucideCircleDollarSign,LucideClock3,LucideFileDown,LucideLandmark,LucideLoaderCircle,LucideLockKeyhole,LucidePlus,LucideReceipt,LucideRefreshCw,LucideWalletCards,LucideX}from'@lucide/angular';import{forkJoin}from'rxjs';import{AuthService}from'../../../../core/auth/auth.service';import{FinanceApiService}from'../../data-access/finance-api.service';import{Account,CashSession,Expense,FinanceDashboard,Payment,PaymentMethod}from'../../models/finance.models';type FinanceTab='accounts'|'payments'|'expenses';
@Component({selector:'app-finance-dashboard',imports:[ReactiveFormsModule,CurrencyPipe,DatePipe,LucideAlertTriangle,LucideArrowDownRight,LucideArrowUpRight,LucideBanknote,LucideCheck,LucideCircleDollarSign,LucideClock3,LucideFileDown,LucideLandmark,LucideLoaderCircle,LucideLockKeyhole,LucidePlus,LucideReceipt,LucideRefreshCw,LucideWalletCards,LucideX],templateUrl:'./finance-dashboard.html',styleUrl:'./finance-dashboard.css',changeDetection:ChangeDetectionStrategy.OnPush})export class FinanceDashboardPage implements OnInit{
 private readonly fb=inject(FormBuilder).nonNullable;private readonly api=inject(FinanceApiService);private readonly auth=inject(AuthService);readonly dashboard=signal<FinanceDashboard|null>(null);readonly accounts=signal<Account[]>([]);readonly methods=signal<PaymentMethod[]>([]);readonly payments=signal<Payment[]>([]);readonly expenses=signal<Expense[]>([]);readonly cash=signal<CashSession|null>(null);readonly loading=signal(true);readonly saving=signal(false);readonly error=signal('');readonly success=signal('');readonly tab=signal<FinanceTab>('accounts');readonly modal=signal<'payment'|'expense'|'open'|'close'|null>(null);readonly selectedAccount=signal<Account|null>(null);readonly canWrite=signal(this.auth.hasPermission('FINANZA_ESCRIBIR'));
 readonly paymentForm=this.fb.group({methodId:this.fb.control<number|null>(null,Validators.required),amount:[0,Validators.min(.01)],reference:['']});readonly expenseForm=this.fb.group({category:['Insumos',Validators.required],description:['',Validators.required],provider:[''],documentReference:[''],methodId:this.fb.control<number|null>(null,Validators.required),amount:[0,Validators.min(.01)]});readonly cashForm=this.fb.group({amount:[0,Validators.min(0)],observation:['']});
 ngOnInit():void{this.load();}
 load():void{const{from,to}=this.range();this.loading.set(true);forkJoin({dashboard:this.api.dashboard(from,to),accounts:this.api.accounts(),methods:this.api.methods(),payments:this.api.payments(from,to),expenses:this.api.expenses(from,to),cash:this.api.currentCash()}).subscribe({next:r=>{this.dashboard.set(r.dashboard);this.accounts.set(r.accounts);this.methods.set(r.methods);this.payments.set(r.payments);this.expenses.set(r.expenses);this.cash.set(r.cash);this.loading.set(false);},error:()=>{this.loading.set(false);this.error.set('No se pudo cargar la información financiera.');}});}
 openPayment(a:Account):void{if(!this.cash()){this.error.set('Abra la caja antes de registrar pagos.');return;}this.selectedAccount.set(a);this.paymentForm.reset({methodId:this.methods()[0]?.id??null,amount:a.balance,reference:''});this.modal.set('payment');this.clear();}
 openExpense():void{if(!this.cash()){this.error.set('Abra la caja antes de registrar gastos.');return;}this.expenseForm.reset({category:'Insumos',description:'',provider:'',documentReference:'',methodId:this.methods()[0]?.id??null,amount:0});this.modal.set('expense');this.clear();}
 openCash():void{this.cashForm.reset({amount:0,observation:''});this.modal.set('open');this.clear();}closeCash():void{this.cashForm.reset({amount:this.cash()?.expectedAmount??0,observation:''});this.modal.set('close');this.clear();}
 savePayment():void{const a=this.selectedAccount();if(!a||this.paymentForm.invalid)return;const v=this.paymentForm.getRawValue(),m=this.methods().find(x=>x.id===v.methodId);if(m?.referenceRequired&&!v.reference.trim()){this.error.set('Este método requiere número de operación o referencia.');return;}if(v.amount>a.balance){this.error.set('El pago no puede superar el saldo.');return;}this.run(this.api.pay(a.id,v.methodId!,v.amount,v.reference.trim()||null),'Pago registrado y constancia generada.');}
 saveExpense():void{if(this.expenseForm.invalid)return;const v=this.expenseForm.getRawValue();this.run(this.api.expense({category:v.category.trim(),description:v.description.trim(),provider:v.provider.trim()||null,documentReference:v.documentReference.trim()||null,paymentMethodId:v.methodId!,amount:v.amount}),'Gasto registrado en caja.');}
 saveCash():void{if(this.cashForm.invalid)return;const v=this.cashForm.getRawValue();const request=this.modal()==='open'?this.api.openCash(v.amount):this.api.closeCash(this.cash()!.id,v.amount,v.observation.trim()||null,this.cash()!.version);this.run(request,this.modal()==='open'?'Caja abierta.':'Caja cerrada y conciliada.');}
 downloadReport():void{const{from,to}=this.range();this.api.exportReport(from,to).subscribe({next:blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Reporte_Dental_Americana.csv';a.click();URL.revokeObjectURL(a.href);},error:()=>this.error.set('No se pudo exportar el reporte.')});}
 closeModal():void{if(!this.saving())this.modal.set(null);}methodNeedsReference():boolean{return this.methods().find(x=>x.id===this.paymentForm.controls.methodId.value)?.referenceRequired??false;}label(v:string):string{return v.replaceAll('_',' ').toLowerCase();}
 private run<T>(request:{subscribe(o:{next(v:T):void;error(e:HttpErrorResponse):void}):unknown},message:string):void{this.saving.set(true);this.clear();request.subscribe({next:()=>{this.saving.set(false);this.modal.set(null);this.success.set(message);this.load();},error:e=>{this.saving.set(false);this.error.set(e.error?.message||'No se pudo registrar la operación.');}});}private range(){const from=new Date();from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+1);return{from:from.toISOString(),to:to.toISOString()};}private clear(){this.error.set('');this.success.set('');}
}
