package pe.com.dentalamericana.odontogram;
import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import pe.com.dentalamericana.odontogram.dto.*;import pe.com.dentalamericana.security.AuthenticatedUser;import java.util.List;
@RestController @RequestMapping("/api/v1")
public class OdontogramController{
 private final OdontogramService service;public OdontogramController(OdontogramService service){this.service=service;}
 @GetMapping("/odontograms") @PreAuthorize("hasAuthority('CLINICA_LEER')") public List<OdontogramResponse> list(@RequestParam Long encounterId){return service.list(encounterId);}
 @PostMapping("/clinical-encounters/{encounterId}/odontograms") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('CLINICA_ESCRIBIR')") public OdontogramResponse initialize(@PathVariable Long encounterId,@Valid @RequestBody OdontogramRequest request,@AuthenticationPrincipal AuthenticatedUser actor,HttpServletRequest http){return service.initialize(encounterId,request,actor,http);}
 @PutMapping("/odontograms/{id}/observation") @PreAuthorize("hasAuthority('CLINICA_ESCRIBIR')") public OdontogramResponse observe(@PathVariable Long id,@Valid @RequestBody OdontogramObservationRequest request,@AuthenticationPrincipal AuthenticatedUser actor,HttpServletRequest http){return service.observe(id,request,actor,http);}
 @PostMapping("/odontograms/{id}/findings") @PreAuthorize("hasAuthority('CLINICA_ESCRIBIR')") public OdontogramResponse finding(@PathVariable Long id,@Valid @RequestBody FindingRequest request,@AuthenticationPrincipal AuthenticatedUser actor,HttpServletRequest http){return service.addFinding(id,request,actor,http);}
 @PatchMapping("/odontograms/{id}/findings/{findingId}/remove") @PreAuthorize("hasAuthority('CLINICA_ESCRIBIR')") public OdontogramResponse remove(@PathVariable Long id,@PathVariable Long findingId,@Valid @RequestBody FindingStatusRequest request,@AuthenticationPrincipal AuthenticatedUser actor,HttpServletRequest http){return service.removeFinding(id,findingId,request,actor,http);}
 @PostMapping("/odontograms/{id}/approve") @PreAuthorize("hasAuthority('CLINICA_APROBAR')") public OdontogramResponse approve(@PathVariable Long id,@Valid @RequestBody ApproveOdontogramRequest request,@AuthenticationPrincipal AuthenticatedUser actor,HttpServletRequest http){return service.approve(id,request,actor,http);}
}
