package pe.com.dentalamericana.copilot;
public enum AiDraftType {
    RESUMEN_HISTORIA,
    BORRADOR_EVOLUCION,
    INDICACIONES_POSTCONSULTA,
    VERIFICACION_CIERRE,
    PLAN_TRATAMIENTO,
    ALERTAS_CLINICAS,
    RESUMEN_PARA_PACIENTE
}
