package pe.com.dentalamericana.user;

public enum PermissionCode {
    USUARIO_LEER,
    USUARIO_ESCRIBIR,
    PACIENTE_LEER,
    PACIENTE_ESCRIBIR,
    CITA_LEER,
    CITA_ESCRIBIR,
    CLINICA_LEER,
    CLINICA_ESCRIBIR,
    CLINICA_APROBAR,
    TRATAMIENTO_LEER,
    TRATAMIENTO_ESCRIBIR,
    FINANZA_LEER,
    FINANZA_ESCRIBIR,
    SEGUIMIENTO_LEER,
    SEGUIMIENTO_ESCRIBIR,
    IA_LEER,
    IA_ESCRIBIR,
    IA_APROBAR,
    AUDITORIA_LEER,
    AJUSTE_ESCRIBIR
}
