package pe.com.dentalamericana.treatment;
import jakarta.servlet.http.HttpServletRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import pe.com.dentalamericana.audit.*;import pe.com.dentalamericana.common.*;import pe.com.dentalamericana.finance.ReceivableAccountService;import pe.com.dentalamericana.patient.*;import pe.com.dentalamericana.security.AuthenticatedUser;import pe.com.dentalamericana.treatment.dto.TreatmentDtos.*;import pe.com.dentalamericana.user.*;import java.math.BigDecimal;import java.util.*;
@Service public class TreatmentService{
 private final pe.com.dentalamericana.clinical.ClinicalEncounterRepository encounters;private final ServiceCatalogRepository services;private final TreatmentPlanRepository plans;private final TreatmentItemRepository items;private final TreatmentEvolutionRepository evolutions;private final PatientService patients;private final AppUserRepository users;private final AuditService audit;private final ReceivableAccountService receivables;
 public TreatmentService(ServiceCatalogRepository services,TreatmentPlanRepository plans,TreatmentItemRepository items,TreatmentEvolutionRepository evolutions,PatientService patients,AppUserRepository users,AuditService audit,ReceivableAccountService receivables,pe.com.dentalamericana.clinical.ClinicalEncounterRepository encounters){this.encounters=encounters;this.services=services;this.plans=plans;this.items=items;this.evolutions=evolutions;this.patients=patients;this.users=users;this.audit=audit;this.receivables=receivables;}
 @Transactional(readOnly=true)public List<ServiceResponse>catalog(){return services.findAllByActivoTrueOrderByCategoriaAscNombreAsc().stream().map(ServiceResponse::from).toList();}
 @Transactional(readOnly=true)public List<PlanResponse>list(Long patientId,Long encounterId){if(patientId!=null)return plans.findAllByPatientIdOrderByCreatedAtDesc(patientId).stream().map(this::response).toList();if(encounterId!=null)return plans.findFirstByEncounterIdOrderByCreatedAtDesc(encounterId).stream().map(this::response).toList();throw new BusinessConflictException("Indique paciente o atención");}
 @Transactional(readOnly=true)public PlanResponse get(Long id){return response(findPlan(id));}
 @Transactional public PlanResponse create(CreatePlanRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);Patient p=patients.find(r.patientId());if(!p.isActive())throw new BusinessConflictException("El paciente está inactivo");if(r.encounterId()!=null){requirePatientEncounter(r.encounterId(),p.getId());var existing=plans.findFirstByEncounterIdOrderByCreatedAtDesc(r.encounterId());if(existing.isPresent())return response(existing.get());}String code="PT-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();TreatmentPlan saved=plans.save(new TreatmentPlan(p.getId(),r.encounterId(),code,trim(r.observations()),actor.getId()));record(actor,"CREAR_PLAN_TRATAMIENTO",saved.getId(),code,http);return response(saved);}
 @Transactional public PlanResponse addItem(Long planId,AddItemRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=requireDraft(planId);ServiceCatalog s=services.findById(r.serviceId()).filter(ServiceCatalog::isActive).orElseThrow(()->new ResourceNotFoundException("Servicio no encontrado"));String description=trim(r.description())==null?s.getName():trim(r.description());items.save(new TreatmentItem(p.getId(),s.getId(),trim(r.tooth()),description,r.quantity(),r.unitPrice(),r.sessions(),actor.getId()));recalculate(p,actor.getId());record(actor,"AGREGAR_ITEM_TRATAMIENTO",p.getId(),s.getName(),http);return response(p);}
 @Transactional public PlanResponse removeItem(Long planId,Long itemId,Long version,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=requireDraft(planId);TreatmentItem item=findItem(planId,itemId);if(!item.getVersion().equals(version))throw new BusinessConflictException("El procedimiento fue modificado");item.deactivate(actor.getId());items.flush();recalculate(p,actor.getId());record(actor,"RETIRAR_ITEM_TRATAMIENTO",p.getId(),"Item "+itemId,http);return response(p);}
 @Transactional public PlanResponse revise(Long id,RevisePlanRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=requireDraft(id);version(p,r.version());if(r.discount().compareTo(p.getSubtotal())>0)throw new BusinessConflictException("El descuento no puede superar el subtotal");p.revise(r.discount(),trim(r.observations()),actor.getId());record(actor,"ACTUALIZAR_PRESUPUESTO",id,"Descuento "+r.discount(),http);return response(p);}
 @Transactional public PlanResponse status(Long id,ChangePlanStatusRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=findPlan(id);version(p,r.version());validatePlanCompletion(p,r.status());validateTransition(p.getStatus(),r.status(),r.patientAcceptance());p.changeStatus(r.status(),r.status()==TreatmentPlanStatus.ACEPTADO&&r.patientAcceptance(),actor.getId());if(r.status()==TreatmentPlanStatus.ACEPTADO){items.findAllByPlanIdAndActivoTrueOrderByIdAsc(id).forEach(i->i.changeStatus(TreatmentItemStatus.ACEPTADO,actor.getId()));receivables.ensureFor(p);}record(actor,"CAMBIAR_ESTADO_PLAN",id,r.status().name(),http);return response(p);}
 @Transactional public PlanResponse itemStatus(Long planId,Long itemId,ChangeItemStatusRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=findPlan(planId);TreatmentItem item=findItem(planId,itemId);if(!item.getVersion().equals(r.version()))throw new BusinessConflictException("El procedimiento fue modificado");if(p.getStatus()!=TreatmentPlanStatus.ACEPTADO&&p.getStatus()!=TreatmentPlanStatus.EN_PROCESO)throw new BusinessConflictException("El plan debe estar aceptado");if(item.getStatus()==TreatmentItemStatus.COMPLETADO||item.getStatus()==TreatmentItemStatus.CANCELADO)throw new BusinessConflictException("El procedimiento ya está cerrado");if(r.status()!=TreatmentItemStatus.EN_PROCESO&&r.status()!=TreatmentItemStatus.COMPLETADO)throw new BusinessConflictException("Estado de procedimiento no permitido");if(r.status()==TreatmentItemStatus.COMPLETADO&&evolutions.findAllByItemIdOrderByFechaDesc(itemId).isEmpty())throw new BusinessConflictException("Registre la evolución antes de completar el procedimiento");item.changeStatus(r.status(),actor.getId());if(r.status()==TreatmentItemStatus.EN_PROCESO&&p.getStatus()==TreatmentPlanStatus.ACEPTADO)p.changeStatus(TreatmentPlanStatus.EN_PROCESO,true,actor.getId());record(actor,"CAMBIAR_ESTADO_TRATAMIENTO",planId,"Item "+itemId+" "+r.status(),http);return response(p);}
 @Transactional public PlanResponse evolution(Long planId,Long itemId,EvolutionRequest r,AuthenticatedUser actor,HttpServletRequest http){requireDentist(actor);TreatmentPlan p=findPlan(planId);TreatmentItem item=findItem(planId,itemId);if(p.getStatus()!=TreatmentPlanStatus.ACEPTADO&&p.getStatus()!=TreatmentPlanStatus.EN_PROCESO)throw new BusinessConflictException("El plan no está aceptado");if(item.getStatus()==TreatmentItemStatus.COMPLETADO||item.getStatus()==TreatmentItemStatus.CANCELADO)throw new BusinessConflictException("El procedimiento ya está cerrado");if(r.encounterId()!=null)requirePatientEncounter(r.encounterId(),p.getPatientId());evolutions.save(new TreatmentEvolution(itemId,r.encounterId(),r.procedure().trim(),trim(r.observations()),r.nextSession(),actor.getId()));item.changeStatus(TreatmentItemStatus.EN_PROCESO,actor.getId());if(p.getStatus()==TreatmentPlanStatus.ACEPTADO)p.changeStatus(TreatmentPlanStatus.EN_PROCESO,true,actor.getId());record(actor,"REGISTRAR_EVOLUCION_TRATAMIENTO",planId,"Item "+itemId,http);return response(p);}

 private void requirePatientEncounter(Long encounterId,Long patientId){
  var encounter=encounters.findById(encounterId).orElseThrow(()->new ResourceNotFoundException("Atención no encontrada"));
  if(!encounter.getPatientId().equals(patientId))throw new BusinessConflictException("La atención no pertenece al paciente del plan");
 }
 private void validatePlanCompletion(TreatmentPlan plan,TreatmentPlanStatus target){
  var procedures=items.findAllByPlanIdAndActivoTrueOrderByIdAsc(plan.getId());
  if((target==TreatmentPlanStatus.PRESENTADO||target==TreatmentPlanStatus.ACEPTADO)&&procedures.isEmpty())throw new BusinessConflictException("Agregue procedimientos antes de presentar o aceptar el plan");
  if(target==TreatmentPlanStatus.COMPLETADO&&(procedures.isEmpty()||procedures.stream().anyMatch(i->i.getStatus()!=TreatmentItemStatus.COMPLETADO)))throw new BusinessConflictException("Complete cada procedimiento antes de cerrar el plan");
 }

 private PlanResponse response(TreatmentPlan p){Patient patient=patients.find(p.getPatientId());String name=String.join(" ",patient.getFirstNames(),patient.getPaternalSurname(),patient.getMaternalSurname()==null?"":patient.getMaternalSurname()).trim();List<ItemResponse>detail=items.findAllByPlanIdAndActivoTrueOrderByIdAsc(p.getId()).stream().map(i->{ServiceCatalog s=services.findById(i.getServiceId()).orElseThrow();return new ItemResponse(i.getId(),s.getId(),s.getName(),i.getTooth(),i.getDescription(),i.getQuantity(),i.getUnitPrice(),i.subtotal(),i.getSessions(),i.getStatus(),i.getVersion(),evolutions.findAllByItemIdOrderByFechaDesc(i.getId()).stream().map(EvolutionResponse::from).toList());}).toList();return new PlanResponse(p.getId(),p.getPatientId(),name,p.getEncounterId(),p.getCode(),p.getStatus(),p.getDiscount(),p.getSubtotal(),p.getTotal(),p.getObservations(),p.isPatientAccepted(),p.getAcceptedAt(),p.getCreatedAt(),p.getUpdatedAt(),p.getVersion(),detail);}
 private void recalculate(TreatmentPlan p,Long actor){BigDecimal subtotal=items.findAllByPlanIdAndActivoTrueOrderByIdAsc(p.getId()).stream().map(TreatmentItem::subtotal).reduce(BigDecimal.ZERO,BigDecimal::add);p.recalculate(subtotal,p.getDiscount().min(subtotal),actor);}
 private void validateTransition(TreatmentPlanStatus from,TreatmentPlanStatus to,boolean accepted){Map<TreatmentPlanStatus,Set<TreatmentPlanStatus>>allowed=Map.of(TreatmentPlanStatus.BORRADOR,Set.of(TreatmentPlanStatus.PRESENTADO,TreatmentPlanStatus.CANCELADO),TreatmentPlanStatus.PRESENTADO,Set.of(TreatmentPlanStatus.ACEPTADO,TreatmentPlanStatus.RECHAZADO,TreatmentPlanStatus.CANCELADO),TreatmentPlanStatus.ACEPTADO,Set.of(TreatmentPlanStatus.EN_PROCESO,TreatmentPlanStatus.CANCELADO),TreatmentPlanStatus.EN_PROCESO,Set.of(TreatmentPlanStatus.COMPLETADO,TreatmentPlanStatus.CANCELADO));if(!allowed.getOrDefault(from,Set.of()).contains(to))throw new BusinessConflictException("Cambio de estado no permitido");if(to==TreatmentPlanStatus.ACEPTADO&&!accepted)throw new BusinessConflictException("Registre la aceptación expresa del paciente");}
 private TreatmentPlan requireDraft(Long id){TreatmentPlan p=findPlan(id);if(p.getStatus()!=TreatmentPlanStatus.BORRADOR)throw new BusinessConflictException("El plan ya no está en borrador");return p;}private TreatmentPlan findPlan(Long id){return plans.findById(id).orElseThrow(()->new ResourceNotFoundException("Plan no encontrado"));}private TreatmentItem findItem(Long p,Long i){return items.findByIdAndPlanIdAndActivoTrue(i,p).orElseThrow(()->new ResourceNotFoundException("Procedimiento no encontrado"));}private void version(TreatmentPlan p,Long v){if(!p.getVersion().equals(v))throw new BusinessConflictException("El plan fue modificado por otro usuario");}private void requireDentist(AuthenticatedUser a){AppUser u=users.findById(a.getId()).orElseThrow();if(u.getRoles().stream().noneMatch(r->r.getCode()==RoleCode.ODONTOLOGO))throw new BusinessConflictException("La acción requiere un odontólogo");}private void record(AuthenticatedUser a,String action,Long id,String detail,HttpServletRequest h){audit.record(patients.actorEntity(a),action,"PLAN_TRATAMIENTO",id.toString(),AuditResult.EXITO,detail,h);}private String trim(String v){return v==null||v.isBlank()?null:v.trim();}
}
