-- Fases 11 y 12: pagos y caja. El modelo reproduce Flyway V7.
create table public.metodos_pago(id bigserial primary key,codigo varchar(30) not null unique,nombre varchar(80) not null,requiere_referencia boolean not null default false,activo boolean not null default true);
insert into public.metodos_pago(codigo,nombre,requiere_referencia)values('EFECTIVO','Efectivo',false),('YAPE','Yape',true),('PLIN','Plin',true),('TRANSFERENCIA','Transferencia bancaria',true),('TARJETA','Tarjeta',true);
create table public.cuentas_por_cobrar(id bigserial primary key,plan_id bigint not null unique references public.planes_tratamiento(id) on delete restrict,paciente_id bigint not null references public.pacientes(id) on delete restrict,monto_total numeric(12,2) not null,monto_pagado numeric(12,2) not null default 0,saldo numeric(12,2) not null,estado varchar(20) not null default 'PENDIENTE',fecha_vencimiento date,creado_en timestamptz not null default current_timestamp,actualizado_en timestamptz not null default current_timestamp,version bigint not null default 0,constraint chk_cuenta_montos check(monto_total>=0 and monto_pagado>=0 and saldo>=0 and saldo=monto_total-monto_pagado),constraint chk_cuenta_estado check(estado in('PENDIENTE','PARCIAL','PAGADA','ANULADA')));
create index idx_cuenta_paciente on public.cuentas_por_cobrar(paciente_id,estado);
create table public.sesiones_caja(id bigserial primary key,abierta_por bigint not null references public.usuarios(id) on delete restrict,abierta_en timestamptz not null default current_timestamp,monto_apertura numeric(12,2) not null,estado varchar(15) not null default 'ABIERTA',cerrada_por bigint references public.usuarios(id) on delete restrict,cerrada_en timestamptz,monto_esperado numeric(12,2),monto_contado numeric(12,2),diferencia numeric(12,2),observacion_cierre varchar(1000),version bigint not null default 0,constraint chk_sesion_estado check(estado in('ABIERTA','CERRADA')),constraint chk_sesion_apertura check(monto_apertura>=0));
create unique index uq_caja_abierta on public.sesiones_caja((estado)) where estado='ABIERTA';
create table public.pagos(id bigserial primary key,cuenta_id bigint not null references public.cuentas_por_cobrar(id) on delete restrict,paciente_id bigint not null references public.pacientes(id) on delete restrict,plan_id bigint not null references public.planes_tratamiento(id) on delete restrict,sesion_caja_id bigint not null references public.sesiones_caja(id) on delete restrict,metodo_pago_id bigint not null references public.metodos_pago(id) on delete restrict,monto numeric(12,2) not null,referencia varchar(120),numero_constancia varchar(30) not null unique,estado varchar(20) not null default 'REGISTRADO',registrado_por bigint not null references public.usuarios(id) on delete restrict,confirmado_por bigint not null references public.usuarios(id) on delete restrict,registrado_en timestamptz not null default current_timestamp,anulado_por bigint references public.usuarios(id),anulado_en timestamptz,motivo_anulacion varchar(500),version bigint not null default 0,constraint chk_pago_monto check(monto>0),constraint chk_pago_estado check(estado in('REGISTRADO','ANULADO')));
create index idx_pago_fecha on public.pagos(registrado_en desc);create index idx_pago_cuenta on public.pagos(cuenta_id,estado);
create table public.gastos(id bigserial primary key,sesion_caja_id bigint not null references public.sesiones_caja(id) on delete restrict,categoria varchar(80) not null,descripcion varchar(500) not null,proveedor varchar(150),documento_referencia varchar(80),metodo_pago_id bigint not null references public.metodos_pago(id),monto numeric(12,2) not null,estado varchar(20) not null default 'REGISTRADO',registrado_por bigint not null references public.usuarios(id),confirmado_por bigint not null references public.usuarios(id),registrado_en timestamptz not null default current_timestamp,anulado_por bigint references public.usuarios(id),anulado_en timestamptz,motivo_anulacion varchar(500),version bigint not null default 0,constraint chk_gasto_monto check(monto>0),constraint chk_gasto_estado check(estado in('REGISTRADO','ANULADO')));
create index idx_gasto_fecha on public.gastos(registrado_en desc);
create table public.movimientos_caja(id bigserial primary key,sesion_caja_id bigint not null references public.sesiones_caja(id),tipo varchar(15) not null,categoria varchar(80) not null,origen varchar(30) not null,origen_id bigint not null,metodo_pago_id bigint references public.metodos_pago(id),monto numeric(12,2) not null,descripcion varchar(500) not null,creado_por bigint not null references public.usuarios(id),creado_en timestamptz not null default current_timestamp,constraint chk_movimiento_tipo check(tipo in('INGRESO','EGRESO')),constraint chk_movimiento_monto check(monto>0));
create index idx_movimiento_sesion on public.movimientos_caja(sesion_caja_id,creado_en);

alter table public.metodos_pago enable row level security;alter table public.cuentas_por_cobrar enable row level security;alter table public.sesiones_caja enable row level security;alter table public.pagos enable row level security;alter table public.gastos enable row level security;alter table public.movimientos_caja enable row level security;
revoke all on public.metodos_pago,public.cuentas_por_cobrar,public.sesiones_caja,public.pagos,public.gastos,public.movimientos_caja from anon,authenticated;
grant select on public.metodos_pago,public.cuentas_por_cobrar,public.sesiones_caja,public.pagos,public.gastos,public.movimientos_caja to authenticated;
create policy payment_methods_read on public.metodos_pago for select to authenticated using(public.has_permission('FINANZA_LEER'));
create policy receivables_read on public.cuentas_por_cobrar for select to authenticated using(public.has_permission('FINANZA_LEER'));
create policy cash_sessions_read on public.sesiones_caja for select to authenticated using(public.has_permission('FINANZA_LEER'));
create policy payments_read on public.pagos for select to authenticated using(public.has_permission('FINANZA_LEER'));
create policy expenses_read on public.gastos for select to authenticated using(public.has_permission('FINANZA_LEER'));
create policy cash_movements_read on public.movimientos_caja for select to authenticated using(public.has_permission('FINANZA_LEER'));

-- Una cuenta se crea exactamente al aceptar el presupuesto, dentro de la misma transacción.
create or replace function public.crear_cuenta_plan_aceptado()returns trigger language plpgsql security definer set search_path='' as $$begin
 if new.estado='ACEPTADO'and old.estado<>'ACEPTADO'then insert into public.cuentas_por_cobrar(plan_id,paciente_id,monto_total,saldo)values(new.id,new.paciente_id,new.total,new.total)on conflict(plan_id)do nothing;end if;return new;end$$;
create trigger cuenta_al_aceptar_plan after update of estado on public.planes_tratamiento for each row execute function public.crear_cuenta_plan_aceptado();
