-- Fase 13: anexos clínicos y archivos privados en Supabase Storage.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('patient-files','patient-files',false,10485760,array['application/pdf','image/jpeg','image/png'])
on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy patient_storage_read on storage.objects for select to authenticated
using(bucket_id='patient-files'and(storage.foldername(name))[1]='pacientes'and(public.has_permission('PACIENTE_LEER')or public.has_permission('CLINICA_LEER')));
create policy patient_storage_insert on storage.objects for insert to authenticated
with check(bucket_id='patient-files'and(storage.foldername(name))[1]='pacientes'and(public.has_permission('PACIENTE_ESCRIBIR')or public.has_permission('CLINICA_ESCRIBIR')));
create policy patient_storage_cleanup on storage.objects for delete to authenticated
using(bucket_id='patient-files'and(storage.foldername(name))[1]='pacientes'and(public.has_permission('PACIENTE_ESCRIBIR')or public.has_permission('CLINICA_ESCRIBIR')));

drop policy patient_files_read_clinical on public.paciente_archivos;
create policy patient_files_read on public.paciente_archivos for select to authenticated
using(public.has_permission('PACIENTE_LEER')or public.has_permission('CLINICA_LEER'));

create or replace function public.agregar_dato_paciente(tipo text,paciente_id bigint,datos jsonb)returns jsonb
language plpgsql security definer set search_path='' as $$declare actor bigint:=public.current_app_user_id();new_id bigint;result jsonb;begin
 if actor is null or not exists(select 1 from public.pacientes p where p.id=paciente_id and p.activo)then raise exception using errcode='P0001',message='Paciente no encontrado o inactivo';end if;
 if tipo='CONTACTO'then if not public.has_permission('PACIENTE_ESCRIBIR')then raise exception using errcode='42501',message='No autorizado';end if;insert into public.paciente_contactos_emergencia(paciente_id,nombre_completo,parentesco,telefono,principal,creado_por)values(paciente_id,btrim(datos->>'fullName'),btrim(datos->>'relationship'),btrim(datos->>'phone'),coalesce((datos->>'primary')::boolean,false),actor)returning id into new_id;select jsonb_build_object('id',c.id,'fullName',c.nombre_completo,'relationship',c.parentesco,'phone',c.telefono,'primary',c.principal,'createdAt',c.creado_en)into result from public.paciente_contactos_emergencia c where c.id=new_id;
 elsif tipo='ANTECEDENTE'then if not public.has_permission('CLINICA_ESCRIBIR')then raise exception using errcode='42501',message='No autorizado';end if;insert into public.paciente_antecedentes(paciente_id,tipo,descripcion,estado,observacion,fecha_informada,creado_por)values(paciente_id,datos->>'type',btrim(datos->>'description'),datos->>'status',nullif(btrim(datos->>'observation'),''),nullif(datos->>'reportedDate','')::date,actor)returning id into new_id;select jsonb_build_object('id',a.id,'type',a.tipo,'description',a.descripcion,'status',a.estado,'observation',a.observacion,'reportedDate',a.fecha_informada,'createdAt',a.creado_en)into result from public.paciente_antecedentes a where a.id=new_id;
 elsif tipo='ALERGIA'then if not public.has_permission('CLINICA_ESCRIBIR')then raise exception using errcode='42501',message='No autorizado';end if;insert into public.paciente_alergias(paciente_id,sustancia,reaccion,severidad,estado,observacion,creado_por)values(paciente_id,btrim(datos->>'substance'),nullif(btrim(datos->>'reaction'),''),datos->>'severity',datos->>'status',nullif(btrim(datos->>'observation'),''),actor)returning id into new_id;select jsonb_build_object('id',a.id,'substance',a.sustancia,'reaction',a.reaccion,'severity',a.severidad,'status',a.estado,'observation',a.observacion,'createdAt',a.creado_en)into result from public.paciente_alergias a where a.id=new_id;
 elsif tipo='MEDICAMENTO'then if not public.has_permission('CLINICA_ESCRIBIR')then raise exception using errcode='42501',message='No autorizado';end if;insert into public.paciente_medicamentos(paciente_id,medicamento,dosis,frecuencia,motivo,fecha_inicio,fecha_fin,vigente,creado_por)values(paciente_id,btrim(datos->>'medication'),nullif(btrim(datos->>'dose'),''),nullif(btrim(datos->>'frequency'),''),nullif(btrim(datos->>'reason'),''),nullif(datos->>'startDate','')::date,nullif(datos->>'endDate','')::date,coalesce((datos->>'current')::boolean,true),actor)returning id into new_id;select jsonb_build_object('id',m.id,'medication',m.medicamento,'dose',m.dosis,'frequency',m.frecuencia,'reason',m.motivo,'startDate',m.fecha_inicio,'endDate',m.fecha_fin,'current',m.vigente,'createdAt',m.creado_en)into result from public.paciente_medicamentos m where m.id=new_id;
 else raise exception using errcode='P0001',message='Tipo de dato de paciente inválido';end if;perform public.registrar_auditoria('AGREGAR_'||tipo,'PACIENTE',paciente_id::text,'Registro '||new_id::text);return result;end $$;

create or replace function public.registrar_archivo_paciente(paciente_id bigint,datos jsonb)returns jsonb language plpgsql security definer set search_path = '' as  $$declare actor bigint:=public.current_app_user_id();item public.paciente_archivos;begin if actor is null or not(public.has_permission('PACIENTE_ESCRIBIR')or public.has_permission('CLINICA_ESCRIBIR'))then raise exception using errcode='42501',message='No autorizado para subir archivos';end if;if not exists(select 1 from public.pacientes p where p.id=paciente_id and p.activo)then raise exception using errcode='P0001',message='El paciente está inactivo';end if;if(datos->>'contentType')not in('application/pdf','image/jpeg','image/png')or(datos->>'sizeBytes')::bigint>10485760 then raise exception using errcode='P0001',message='Solo se permiten PDF, JPG y PNG de hasta 10 MB';end if;insert into public.paciente_archivos(paciente_id,categoria,nombre_original,nombre_interno,tipo_contenido,tamano_bytes,ubicacion,descripcion,creado_por)values(paciente_id,datos->>'category',datos->>'originalName',datos->>'path',datos->>'contentType',(datos->>'sizeBytes')::bigint,datos->>'path',nullif(btrim(datos->>'description'),''),actor)returning*into item;perform public.registrar_auditoria('SUBIR_ARCHIVO_PACIENTE','PACIENTE',paciente_id::text,'Archivo '||item.id::text);return jsonb_build_object('id',item.id,'category',item.categoria,'originalName',item.nombre_original,'contentType',item.tipo_contenido,'sizeBytes',item.tamano_bytes,'description',item.descripcion,'createdAt',item.creado_en);end $$;
create or replace function public.auditar_descarga_archivo(paciente_id bigint,archivo_id bigint)returns text language plpgsql security definer set search_path = '' as  $$declare path text;begin if not(public.has_permission('PACIENTE_LEER')or public.has_permission('CLINICA_LEER'))then raise exception using errcode='42501',message='No autorizado para descargar archivos';end if;select ubicacion into path from public.paciente_archivos where id=archivo_id and paciente_id=auditar_descarga_archivo.paciente_id and activo;if path is null then raise exception using errcode='P0001',message='Archivo no encontrado';end if;perform public.registrar_auditoria('DESCARGAR_ARCHIVO_PACIENTE','PACIENTE',paciente_id::text,'Archivo '||archivo_id::text);return path;end $$;

revoke all on function public.agregar_dato_paciente(text,bigint,jsonb),public.registrar_archivo_paciente(bigint,jsonb),public.auditar_descarga_archivo(bigint,bigint)from public;
grant execute on function public.agregar_dato_paciente(text,bigint,jsonb),public.registrar_archivo_paciente(bigint,jsonb),public.auditar_descarga_archivo(bigint,bigint)to authenticated;
