-- Fases 14-17: seguimiento, WhatsApp, administración y copiloto IA supervisado.
create table public.plantillas_mensaje(id bigserial primary key,codigo varchar(50) not null unique,nombre varchar(100) not null,categoria varchar(40) not null,contenido text not null,activo boolean not null default true,creado_en timestamptz not null default current_timestamp,actualizado_en timestamptz not null default current_timestamp,version bigint not null default 0);
insert into public.plantillas_mensaje(codigo,nombre,categoria,contenido)values
('CITA_CONFIRMACION','Confirmación de cita','CITA','Hola {{paciente}}, tiene una cita el {{fecha}} a las {{hora}}. Responda CONFIRMO o solicite reprogramación.'),
('CITA_RECORDATORIO','Recordatorio de cita','CITA','Le recordamos su cita de mañana a las {{hora}} en Consultorio Dental Americana.'),
('POSTCONSULTA','Seguimiento postconsulta','SEGUIMIENTO','Hola {{paciente}}, ¿cómo se siente después de su atención? Puede responder con sus propias palabras.');
create table public.conversaciones_whatsapp(id bigserial primary key,paciente_id bigint references public.pacientes(id) on delete restrict,telefono varchar(20) not null,estado varchar(20) not null default 'ABIERTA',ultimo_mensaje_en timestamptz,creado_en timestamptz not null default current_timestamp,actualizado_en timestamptz not null default current_timestamp,constraint chk_conversacion_estado check(estado in('ABIERTA','DERIVADA','CERRADA')));
create unique index uq_conversacion_telefono_abierta on public.conversaciones_whatsapp(telefono)where estado<>'CERRADA';
create table public.mensajes_whatsapp(id bigserial primary key,conversacion_id bigint not null references public.conversaciones_whatsapp(id) on delete restrict,paciente_id bigint references public.pacientes(id) on delete restrict,cita_id bigint references public.citas(id) on delete restrict,atencion_id bigint references public.atenciones_clinicas(id) on delete restrict,direccion varchar(10) not null,contenido text not null,estado varchar(20) not null,programado_para timestamptz,proveedor_id varchar(150),intencion varchar(40),requiere_revision boolean not null default false,error_detalle varchar(500),creado_por bigint references public.usuarios(id),creado_en timestamptz not null default current_timestamp,enviado_en timestamptz,tipo varchar(40) not null default 'MANUAL',plantilla_nombre varchar(120),parametros_plantilla jsonb not null default'[]'::jsonb,intentos integer not null default 0,max_intentos integer not null default 3,ultimo_intento_en timestamptz,constraint chk_mensaje_direccion check(direccion in('ENTRANTE','SALIENTE')),constraint chk_mensaje_estado check(estado in('PENDIENTE','ENVIADO','ENTREGADO','LEIDO','RECIBIDO','FALLIDO','CANCELADO')),constraint chk_mensaje_tipo check(tipo in('ENTRANTE','CITA_CONFIRMACION','CITA_RECORDATORIO','POSTCONSULTA','MANUAL')),constraint chk_mensaje_intentos check(intentos>=0 and max_intentos between 1 and 10 and intentos<=max_intentos));
create unique index uq_mensaje_proveedor on public.mensajes_whatsapp(proveedor_id)where proveedor_id is not null;create index idx_mensaje_programado on public.mensajes_whatsapp(estado,programado_para);create index idx_mensaje_conversacion on public.mensajes_whatsapp(conversacion_id,creado_en desc);
create table public.seguimientos_postconsulta(id bigserial primary key,paciente_id bigint not null references public.pacientes(id) on delete restrict,atencion_id bigint not null references public.atenciones_clinicas(id) on delete restrict,mensaje_id bigint references public.mensajes_whatsapp(id) on delete restrict,programado_para timestamptz not null,estado varchar(20) not null default 'PROGRAMADO',respuesta text,clasificacion varchar(40),motivo_alerta varchar(500),revisado_por bigint references public.usuarios(id),revisado_en timestamptz,creado_por bigint not null references public.usuarios(id),creado_en timestamptz not null default current_timestamp,actualizado_en timestamptz not null default current_timestamp,version bigint not null default 0,constraint chk_seguimiento_estado check(estado in('PROGRAMADO','ENVIADO','RESPONDIDO','ALERTA','REVISADO','CERRADO')),unique(atencion_id));create index idx_seguimiento_estado on public.seguimientos_postconsulta(estado,programado_para);

insert into public.permisos(codigo,descripcion)values('IA_LEER','Consultar borradores y verificaciones del copiloto'),('IA_ESCRIBIR','Generar borradores con el copiloto'),('IA_APROBAR','Aprobar o rechazar borradores clínicos del copiloto')on conflict(codigo)do nothing;
insert into public.roles_permisos(rol_id,permiso_id)select r.id,p.id from public.roles r join public.permisos p on p.codigo in('IA_LEER','IA_ESCRIBIR','IA_APROBAR')where r.codigo in('ADMINISTRADOR','ODONTOLOGO')on conflict do nothing;
create table public.borradores_ia(id bigserial primary key,atencion_id bigint not null references public.atenciones_clinicas(id),paciente_id bigint not null references public.pacientes(id),tipo varchar(40) not null,estado varchar(20) not null default'BORRADOR',contenido text not null,datos_fuente jsonb not null,campos_faltantes jsonb not null default'[]'::jsonb,advertencia varchar(500) not null,motivo_rechazo varchar(500),generado_por bigint not null references public.usuarios(id),generado_en timestamptz not null default current_timestamp,revisado_por bigint references public.usuarios(id),revisado_en timestamptz,version bigint not null default 0,constraint chk_borrador_estado check(estado in('BORRADOR','APROBADO','RECHAZADO')),constraint chk_borrador_tipo check(tipo in('RESUMEN_HISTORIA','BORRADOR_EVOLUCION','INDICACIONES_POSTCONSULTA','VERIFICACION_CIERRE','PLAN_TRATAMIENTO','ALERTAS_CLINICAS','RESUMEN_PARA_PACIENTE')));create index idx_borradores_ia_atencion on public.borradores_ia(atencion_id,generado_en desc);create index idx_borradores_ia_estado on public.borradores_ia(estado,generado_en desc);

create table public.configuracion_sistema(clave varchar(80) primary key,valor varchar(500) not null,descripcion varchar(250) not null,actualizado_por bigint references public.usuarios(id),actualizado_en timestamptz not null default current_timestamp,version bigint not null default 0);
insert into public.configuracion_sistema(clave,valor,descripcion)values('clinica.nombre','Consultorio Dental Americana','Nombre comercial mostrado en documentos y pantallas'),('clinica.ruc','','RUC del consultorio; completar antes de emitir documentos'),('clinica.direccion','Av. Mariscal Cáceres N.° 1072, 2.° nivel, Ayacucho','Dirección pública del establecimiento'),('clinica.telefono','940 577 075','Número principal de contacto'),('clinica.horario','Lunes a sábado, previa cita','Horario público de atención'),('clinica.zona_horaria','America/Lima','Zona horaria usada por agenda y recordatorios');

alter table public.plantillas_mensaje enable row level security;alter table public.conversaciones_whatsapp enable row level security;alter table public.mensajes_whatsapp enable row level security;alter table public.seguimientos_postconsulta enable row level security;alter table public.borradores_ia enable row level security;alter table public.configuracion_sistema enable row level security;
revoke all on public.plantillas_mensaje,public.conversaciones_whatsapp,public.mensajes_whatsapp,public.seguimientos_postconsulta,public.borradores_ia,public.configuracion_sistema from anon,authenticated;
grant select on public.plantillas_mensaje,public.conversaciones_whatsapp,public.mensajes_whatsapp,public.seguimientos_postconsulta to authenticated;grant select on public.borradores_ia to authenticated;grant select on public.configuracion_sistema to authenticated;
create policy templates_read on public.plantillas_mensaje for select to authenticated using(public.has_permission('SEGUIMIENTO_LEER'));create policy conversations_read on public.conversaciones_whatsapp for select to authenticated using(public.has_permission('SEGUIMIENTO_LEER'));create policy messages_read on public.mensajes_whatsapp for select to authenticated using(public.has_permission('SEGUIMIENTO_LEER'));create policy followups_read on public.seguimientos_postconsulta for select to authenticated using(public.has_permission('SEGUIMIENTO_LEER'));create policy ai_drafts_read on public.borradores_ia for select to authenticated using(public.has_permission('IA_LEER'));create policy settings_read on public.configuracion_sistema for select to authenticated using(public.has_permission('USUARIO_LEER')or public.has_permission('AJUSTE_ESCRIBIR'));

do $$begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='citas')then alter publication supabase_realtime add table public.citas;end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='mensajes_whatsapp')then alter publication supabase_realtime add table public.mensajes_whatsapp;end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='seguimientos_postconsulta')then alter publication supabase_realtime add table public.seguimientos_postconsulta;end if;
end $$;
